#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bastcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x2a,0x01,0xcb,0x00,0x08,0xd5,0x61,0x00,0x29,0x4c,0xdd,0x5e,0x5e,0x42,0xf0,0x85}, 7333}
    
};

static SeedSpec6 pnSeed6_test[] = {
    
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
